# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/SampleCode;/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/opt/clion-2021.1.1/bin/cmake/linux/share/cmake-3.19/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "SampleCode built using CMake")
set(CPACK_EXTERNAL_ENABLE_STAGING "1")
set(CPACK_EXTERNAL_PACKAGE_SCRIPT "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy/CubeSample/apk_bundle_RedCubeSample/package.cmake")
set(CPACK_GENERATOR "External")
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY "OFF")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy;CubeSample;RedCubeSampleComponent;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "RedCubeSample 2.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "RedCubeSample 2.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy/CubeSample/apk_bundle_RedCubeSample/CPackConfigRedCubeSampleComponent.cmake")
set(CPACK_PACKAGE_CONTACT "<hal9000@snapchat.com>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/opt/clion-2021.1.1/bin/cmake/linux/share/cmake-3.19/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "SampleCode built using CMake")
set(CPACK_PACKAGE_DIRECTORY "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy/CubeSample/apk_bundle_RedCubeSample/package_directory")
set(CPACK_PACKAGE_FILE_NAME "RedCubeSample-2.0.0-Android")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "RedCubeSample 2.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "RedCubeSample 2.0.0")
set(CPACK_PACKAGE_NAME "RedCubeSample")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "SNAP")
set(CPACK_PACKAGE_VERSION "2.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_RESOURCE_FILE_LICENSE "/opt/clion-2021.1.1/bin/cmake/linux/share/cmake-3.19/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/opt/clion-2021.1.1/bin/cmake/linux/share/cmake-3.19/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/opt/clion-2021.1.1/bin/cmake/linux/share/cmake-3.19/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "ON")
set(CPACK_SYSTEM_NAME "Android")
set(CPACK_TOPLEVEL_TAG "Android")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/m4zz31/Snapchat/Dev/spectacles-native-sdk/ShaderToy/ShaderToy/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
